### ISSUE TITLE
'Gentle introduction' is inaccessible

### ISSUE THREAD

**Issue by michmech** [elexis-eu/lexonomy#147]
Go to this URL (or click the 'Gentle introduction' link on the homepage) and you get 404 Not Found:

https://www.lexonomy.eu/docs/intro/

Probably these lines in lexonomy.py is causing it by thinking that everything in the docs directory are static files:

```
# serve static files
@route('/<path:re:(widgets|furniture|libs|docs).*>')
def server_static(path):
    return static_file(path, root="./")
```

Not everything in the docs directory is a static file.

**Comment by iiegn** [comment]
...how is this actually supposed to work (or how did it work)? 

there exists a markdown file `intro.md` which links to, i think, all the `0x-0y.png` files but not, for example,
 - `lexonomy_httpd.con`
 - `mode-laic.png`
 - `text-editor-asklongstring.png`
 - `web.config`
...
now, how is this markdown file supposed to become 'rendered'? 
 - is this something we introduced when moving the 'wiki' from github into this repository (because obviously, a `.md` file in a wiki on github would get rendered)
 - do we need to 'render this' 
   - offline (ideally automatically before/during git commit)?
   - online?

**Comment by michmech** [comment]
In the Node.js backend this is (or rather: was) handled in the following way.

1. There is (or rather: was) a line of code in lexonomy.js that says that static files can be found in the `/docs` directory (as well as a couple of other locations). If an HTTP request arrives asking for something in this directory, and if such a file exists there, then Node,.js serves this file. If not, then Node.js proceeds to number 2.

2. There is a GET handler in lexonomy.js (lines 220 - 226) which handles requests to URLs like `/docs/blablabla/.` The handler assumes that a file like `docs/blablabla.md` exists, opens it, converts it contents from Markdown to HTML, and serves it to the user through the template `views/doc.ejs`.

**Comment by iiegn** [comment]
> In the Node.js backend this is (or rather: was) handled in the following way.
> 
> 1. There is (or rather: was) a line of code in lexonomy.js that says that static files can be found in the `/docs` directory (as well as a couple of other locations). If an HTTP request arrives asking for something in this directory, and if such a file exists there, then Node,.js serves this file. If not, then Node.js proceeds to number 2.

ok, likely around here (just for reference): 9eaa7c946f1573db9a120761ec2ba5ae196dc2c8

> 2. There is a GET handler in lexonomy.js (lines 220 - 226) which handles requests to URLs like `/docs/blablabla/.` The handler assumes that a file like `docs/blablabla.md` exists, opens it, converts it contents from Markdown to HTML, and serves it to the user through the template `views/doc.ejs`.

and this one, for reference, as well:
https://github.com/elexis-eu/lexonomy/blob/0e0d68b8dd106e7539617a9be8bd0419fc0f784e/website/lexonomy.js#L219-L226

So far, it seems, we have keept the [EJS templating](https://ejs.co/) in place. Insofar, we could 
 - (re)use the existing EJS templates
 - and use (something like) https://github.com/Python-Markdown/markdown to insert HTML (of the markdown) on the fly

(possible) alternative:
 - use bottle's templating engine (but this would probably only make sense if we wanted to move away more parts - and not only docs/)
 - other ideas...

@mjakubicek have you given this already a thought?

**Comment by mjakubicek** [comment]
short term solution is just to forward requests to this path to NodeJS
long term is rewrite for the bottlepy templates like everything else (so far there is just one template in bottlepy - the consent.tpl)

**Comment by michmech** [comment]
Embarrassingly, it still isn't working:
https://www.lexonomy.eu/docs/intro/

**Comment by iiegn** [comment]
ok, i see - but this time it's a 'deployment' issue: 'someone' needs to update https://www.lexonomy.eu because https://lexonomy.elex.is works.
(i think, we can stuff it into this issue for the time being - generally, i'd consider it a different issue...)

**Comment by rambousek** [comment]
This is already fixed in beta

**Comment by jsbien** [comment]
Today https://www.lexonomy.eu/docs/intro/ is still not working.

**Comment by rambousek** [comment]
Thanks for information, somehow we drop intro in the new interface. It is back in now
